# -*- coding: utf-8 -*-
"""exp3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TVhSFb1gOzN_ZJypuqX7Na82Rs7fuCWI
"""

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from generate_1 import fetch_greedy_decoding, fetch_sampling, fetch_temperature_sampling, fetch_nucleus_sampling, beam_search

if __name__ == "__main__":
    device = "cuda"

    model = AutoModelForCausalLM.from_pretrained('Qwen/Qwen2.5-0.5B-Instruct').eval()
    tokenizer = AutoTokenizer.from_pretrained('Qwen/Qwen2.5-0.5B-Instruct')

    hedgehog_prompt = '<|im_start|>system\nYou are a storyteller. Generate a story based on user message.<|im_end|>\n<|im_start|>user\nGenerate me a short story about a tiny hedgehog named Sonic.<|im_end|>\n<|im_start|>assistant\n'
    json_prompt = '<|im_start|>system\nYou are a JSON machine. Generate a JSON with format {"contractor": string with normalized contractor name, "sum": decimal, "currency": string with uppercased 3-letter currency code} based on user message.<|im_end|>\n<|im_start|>user\nTransfer 100 rubles and 50 kopeck to Mike<|im_end|>\n<|im_start|>assistant\n'

    hedgehog_story_greedy = fetch_greedy_decoding(model, tokenizer, input_prompt=hedgehog_prompt, max_tokens=1000, device=device)
    hedgehog_story_text_greedy = tokenizer.decode(hedgehog_story_greedy, skip_special_tokens=True)

    json_response_greedy = fetch_greedy_decoding(model, tokenizer, input_prompt=json_prompt, max_tokens=1000, device=device)
    json_response_text_greedy = tokenizer.decode(json_response_greedy, skip_special_tokens=True)

    print("Сказка про Соника (жадное декодирование):")
    print(hedgehog_story_text_greedy)
    print("\nСгенерированный JSON (жадное декодирование):")
    print(json_response_text_greedy)

    hedgehog_story_sampled = fetch_sampling(model, tokenizer, input_prompt=hedgehog_prompt, max_tokens=1000, device=device)
    hedgehog_story_text_sampled = tokenizer.decode(hedgehog_story_sampled, skip_special_tokens=True)

    json_response_sampled = fetch_sampling(model, tokenizer, input_prompt=json_prompt, max_tokens=1000, device=device)
    json_response_text_sampled = tokenizer.decode(json_response_sampled, skip_special_tokens=True)

    print("\nСказка про Соника (сэмплинг):")
    print(hedgehog_story_text_sampled)
    print("\nСгенерированный JSON (сэмплинг):")
    print(json_response_text_sampled)

    temperatures = [0.001, 0.1, 0.5, 1.0, 10.0]
    for temp in temperatures:
        hedgehog_story_temp = fetch_temperature_sampling(model, tokenizer, input_prompt=hedgehog_prompt, max_tokens=1000, temperature=temp, device=device)
        hedgehog_story_text_temp = tokenizer.decode(hedgehog_story_temp, skip_special_tokens=True)

        json_response_temp = fetch_temperature_sampling(model, tokenizer, input_prompt=json_prompt, max_tokens=1000, temperature=temp, device=device)
        json_response_text_temp = tokenizer.decode(json_response_temp, skip_special_tokens=True)

        print(f"\nСказка про Соника (сэмплинг с температурой {temp}):")
        print(hedgehog_story_text_temp)
        print(f"\nСгенерированный JSON (сэмплинг с температурой {temp}):")
        print(json_response_text_temp)